version: "3"

services:
  keycloak:
    image: jboss/keycloak:15.1.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true 

networks:
  default:
    name: sample-local-nw
    external: true
